# Generated by Django 3.2.4 on 2021-06-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('website', models.CharField(default='NA', max_length=500)),
                ('image', models.ImageField(default='images/none/no_image.png', upload_to='images/')),
            ],
        ),
    ]
